routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('wechat',   'WechatController@serve');
Route::any('create-menu',   'WechatController@createMenu');


Route::get('test','IndexController@test');


Route::get('login',     'IndexController@login');
Route::any('logindo',   'IndexController@loginDo');
Route::middleware(['wechat.oauth'])->group(function(){
	
	Route::middleware(['checkUser'])->group(function(){ 	
	 	Route::get('/',         'IndexController@index');
	 	Route::get('query-flow','IndexController@queryFlow');
	 	Route::get('offer-dtl', 'IndexController@offerDtl');
	 	Route::any('recharge',  'IndexController@recharge');
	 	Route::get('log','IndexController@log');
	});
});



//Route::middleware(['web','wechat.oauth'])->prefix('user')->group(function(){	
	
//});

Route::prefix('zadmin')->namespace('Admin')->group(function(){
	Route::middleware('checkAdmin')->group(function(){
		
		
		Route::resource('cards',      'CardController');   // 物联卡
		Route::resource('users',      'UserController');  
		Route::resource('dataplans',  'DataplanController'); //套餐
		Route::resource('orders',     'OrderController');
		
		//后台首页
		Route::get('/',		   'IndexController@index');
		
	});
		Route::get('login',    'LoginController@login');
		Route::post('logindo', 'LoginController@loginDo');
		Route::get('logout',   'LoginController@logOut');
		
	
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = ['id'];

    public function dataplan()
    {
    	return $this->belongsTo(Dataplan::class);
    }

    public function getPriceTxtAttribute()
    {
    	return $this->price/100;
    }

}

resources/views/front/head.blade.php
<div class="head-box clearfix">
    <div class="head-img-box"><img src="{{session('user')->avatar}}" alt="" class="img-circle head-img"></div>
    <div class="member-name-box">
        <p>昵称：{{session('user')->nickname}}</p>
        <p style="word-break:break-all;">卡号：{{session('user')->iccid}}</p>
    </div>
</div>

resources/views/front/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--1.width=device-width    //应用程序的宽度和屏幕的宽度是一样的
2.height=device-height  //应用程序的高度和屏幕的高是一样的
3.initial-scale=1.0  //应用程序启动时候的缩放尺度（1.0表示不缩放）
4.minimum-scale=1.0  //用户可以缩放到的最小尺度（1.0表示不缩放）
5.maximum-scale=1.0  //用户可以放大到的最大尺度（1.0表示不缩放）
6.user-scalable=no  //用户是否可以通过他的手势来缩放整个应用程序，使应用程序的尺度发生一个改变（yes/no）
    -->
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <link rel="stylesheet" href="/front/bootstrap-3.3.6-dist/css/bootstrap.min.css">

    <title>个人中心</title>
    <style>
        *{
            marign:0;
            padding:0
        }
        li{
            list-style: none;
        }
        body {
            background: #f0f1f3;
            font-size: 14px;
        }
        .text-orange{
            color:#FF7F42;
        }
        .head-box {
            padding: 20px 15px;
            background: #0d73bd url("/front/bg.png");
            background-size: cover;
        }

        .head-img-box {
            margin-right: 2%;
            float: left;
        }

        .head-img {
            width: 80px;
            height: 80px;
        }

        .member-name-box {
            width: 70%;
            margin: 12px 0 0 0;
            float: left;
            font-size: 14px;
            color: #fff;
        }
        .account-box{
            width:100%;
            height:46px;
            line-height: 46px;
            display:flex;
        }
        .account-box li{
            float:left;
            flex:1;
            background: #fff;
            text-align: center;
        }
        .account-box li:first-child{
            margin-right:2px;
        }
        .menu-box{
            margin-top:15px;
        }
        .menu-box li{
            width:33%;
            margin:0 1px 1px 0;
            padding:20px 0;
            float:left;
            background: #fff;
            font-size:16px;
            color:#333;
            text-align: center;
        }
        .menu-box li:last-child(3),
        .menu-box li:last-child{
            margin-right:0;
        }
        .menu-box li .menu-icon{
            display: block;
            width:38px;
            height:38px;
            margin:0 auto 5px auto;
        }
    </style>
</head>
<body>
@include('front.head')
<!-- <ul class="account-box clearfix">
    <li>账户余额：<span class="text-primary">0</span> 元</li>
    <li>认证状态：<span class="text-orange">未认证</span></li>
</ul> -->
<ul class="menu-box clearfix">
    <li>
        <a href="{{url('query-flow')}}">
            <img src="/front/liuliang.png" alt="" class="menu-icon">流量查询
        </a>    
    </li>
    <li>
        <a href="{{url('offer-dtl')}}">
            <img src="/front/dinggou.png" alt="" class="menu-icon">流量订购
        </a>
    </li>
    <li>
        <a href="{{url('log')}}">
        <img src="/front/xiaofei.png" alt="" class="menu-icon">消费记录
        </a>
    </li>
   <!--  <li><img src="/front/renzheng.png" alt="" class="menu-icon">实名认真</li>
    <li><img src="/front/chongzhi.png" alt="" class="menu-icon">余额充值</li>
    <li><img src="/front/jiebang.png" alt="" class="menu-icon">电信机卡解绑</li> -->
</ul>
<script src="/front/bootstrap-3.3.6-dist/js/jquery.min.js"></script>
<script src="/front/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/front/log.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--1.width=device-width    //应用程序的宽度和屏幕的宽度是一样的
2.height=device-height  //应用程序的高度和屏幕的高是一样的
3.initial-scale=1.0  //应用程序启动时候的缩放尺度（1.0表示不缩放）
4.minimum-scale=1.0  //用户可以缩放到的最小尺度（1.0表示不缩放）
5.maximum-scale=1.0  //用户可以放大到的最大尺度（1.0表示不缩放）
6.user-scalable=no  //用户是否可以通过他的手势来缩放整个应用程序，使应用程序的尺度发生一个改变（yes/no）
    -->
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <link rel="stylesheet" href="/front/bootstrap-3.3.6-dist/css/bootstrap.min.css">

    <title>个人中心</title>
    <style>
        *{
            marign:0;
            padding:0
        }
        li{
            list-style: none;
        }
        body {
            background: #f0f1f3;
            font-size: 14px;
        }
        .text-orange{
            color:#FF7F42;
        }
        .head-box {
            padding: 20px 15px;
            background: #0d73bd url("bg.png");
            background-size: cover;
        }

        .head-img-box {
            margin-right: 2%;
            float: left;
        }

        .head-img {
            width: 80px;
            height: 80px;
        }

        .member-name-box {
            width: 70%;
            margin: 12px 0 0 0;
            float: left;
            font-size: 14px;
            color: #fff;
        }
        .account-box{
            width:100%;
            height:46px;
            line-height: 46px;
            display:flex;
        }
        .account-box li{
            float:left;
            flex:1;
            background: #fff;
            text-align: center;
        }
        .account-box li:first-child{
            margin-right:2px;
        }
        .menu-box{
            margin-top:15px;
        }
        .menu-box li{
            width:33%;
            margin:0 1px 1px 0;
            padding:20px 0;
            float:left;
            background: #fff;
            font-size:16px;
            color:#333;
            text-align: center;
        }
        .menu-box li:last-child(3),
        .menu-box li:last-child{
            margin-right:0;
        }
        .menu-box li .menu-icon{
            display: block;
            width:38px;
            height:38px;
            margin:0 auto 5px auto;
        }
    </style>
</head>
<body>
<div class="head-box clearfix">
    <div class="head-img-box"><img src="{{session('user')->avatar}}" alt="" class="img-circle head-img"></div>
    <div class="member-name-box">
        <p>昵称：{{session('user')->nickname}}</p>
        <p style="word-break:break-all;">卡号：{{session('user')->iccid}}</p>
    </div>
</div>
<!-- <ul class="account-box clearfix">
    <li>账户余额：<span class="text-primary">0</span> 元</li>
    <li>认证状态：<span class="text-orange">未认证</span></li>
</ul> -->
@if($list)
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">充值记录</div>

  <!-- Table -->
  <table class="table">
    <tr>
        <td>时间</td>
        <td>金额</td>
        <td>事项</td>
    </tr>
    @foreach($list as $v)
    <tr>
        <td>{{$v->created_at}}</td>
        <td>{{$v->price_txt}}</td>
        <td>{{$v->msg}}</td>
    </tr>
    @endforeach
   
    
  </table>
  {{$list->links()}}
  <div style="float: right;margin-right:10px; ">
    <a href="{{url('/')}}" class="btn btn-primary navbar-btn">返回</a>
  </div>
</div>
@else
<div class="alert alert-info" role="alert">没有查询到充值记录</div>
@endif
<script src="/front/bootstrap-3.3.6-dist/js/jquery.min.js"></script>
<script src="/front/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/front/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--1.width=device-width    //应用程序的宽度和屏幕的宽度是一样的
2.height=device-height  //应用程序的高度和屏幕的高是一样的
3.initial-scale=1.0  //应用程序启动时候的缩放尺度（1.0表示不缩放）
4.minimum-scale=1.0  //用户可以缩放到的最小尺度（1.0表示不缩放）
5.maximum-scale=1.0  //用户可以放大到的最大尺度（1.0表示不缩放）
6.user-scalable=no  //用户是否可以通过他的手势来缩放整个应用程序，使应用程序的尺度发生一个改变（yes/no）
    -->
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.1.0/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/front/iconfont/iconfont.css">
    <title>登录</title>
    <style>
        * {
            marign: 0;
            padding: 0;
            overflow: hidden;
        }

        html, body {
            width: 100%;
            height: 100%;
        }

        body {
            /*background:#0a6dbe;*/
            background: #0d73bd url("/front/bg.png") no-repeat;
            background-size: cover;
        }

        .login-icon {
            display: block;
            width: 130px;
            height: 130px;
            margin: 20px auto;
        }

        .login-box {
            width: 80%;
            margin: 0 auto;
            padding-top: 20%;
        }

        .input-box {
            margin: 10px 0;
            border-bottom: 1px solid rgba(255, 255, 255, 0.4);
        }

        .icon-input {
            display: inline-block;
            margin-right:5px;
            font-size: 16px;
            color: #fff;
            opacity: 0.6;
        }

        .noboder-input {
            height: 46px;
            line-height: 46px;
            background: transparent;
            border: none;
            outline: none;
            font-size: 16px;
            color: #fff;
        }

        .noboder-input::-webkit-input-placeholder { /* WebKit browsers */
            color: #fff;
        }

        .noboder-input:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
            color: #fff;
        }

        .noboder-input::-moz-placeholder { /* Mozilla Firefox 19+ */
            color: #fff;
        }

        .noboder-input:-ms-input-placeholder { /* Internet Explorer 10+ */
            color: #fff;
        }

        .noboder-input:focus::-webkit-input-placeholder { /* WebKit browsers */
            color: transparent;
        }

        .noboder-input:focus:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
            color: transparent;
        }

        .noboder-input:focus::-moz-placeholder { /* Mozilla Firefox 19+ */
            color: transparent;
        }

        .noboder-input:focus:-ms-input-placeholder { /* Internet Explorer 10+ */
            color: transparent;
        }
        .button-box{
            width:90%;
            margin: 30px auto 0 auto;
        }
        .login-btn{
            width:100%;
            height:48px;
            font-size:20px;
            letter-spacing:10px;
            display: block;
            text-align: center;
            border:none;
            border-radius: 3px;
            background: rgba(255, 255, 255,0.4);
            color: rgba(255, 255, 255,0.8);
            font-weight:400;
        }
        .link-btn{
            margin-top:10px;
            display: block;
            float:right;
            font-size:12px;
            color:#afdef5;
        }
    </style>
</head>
<body>

<img src="/front/login-icon.png" alt="" class="login-icon">
<form action="{{url('logindo')}}" class="login-box">
@if(session('rs'))
<div class="alert alert-{{session('rs')['status']}}">
  {{ session('rs')['msg'] }}
</div>
@endif  
    <div class="input-box">
        <span class="icon-input iconfont icon-shoujihao1"></span>
        <input type="text" name="iccid" class="noboder-input" placeholder="请输入卡号">
    </div>
  <!--   <div class="input-box">
        <span class="icon-input iconfont icon-mima"></span>
        <input type="password" class="noboder-input" placeholder="请输入密码">
    </div> -->
    <div class="button-box clearfix">
        <button class="login-btn" type="button"> 登录</button>
        <!-- <a href="" class="link-btn">忘记密码</a> -->
    </div>
</form>
</body>
</html>
<script src="/front/bootstrap-3.3.6-dist/js/jquery.min.js"></script>
<script type="text/javascript">
    $(function(){
        var iccid  = localStorage.getItem("iccid");
        if(iccid) {
            $('input[name="iccid"]').val(iccid);    
        }
        
    });
    $('.login-btn').on('click',function(){
        var iccid = $('input[name="iccid"]').val();
        if(!iccid) {
            alert('请先输入卡号');return false;
        }
        localStorage.setItem('iccid', iccid);
        $('.login-box').submit();
    });
</script>

resources/views/front/offerdtl.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--1.width=device-width    //应用程序的宽度和屏幕的宽度是一样的
2.height=device-height  //应用程序的高度和屏幕的高是一样的
3.initial-scale=1.0  //应用程序启动时候的缩放尺度（1.0表示不缩放）
4.minimum-scale=1.0  //用户可以缩放到的最小尺度（1.0表示不缩放）
5.maximum-scale=1.0  //用户可以放大到的最大尺度（1.0表示不缩放）
6.user-scalable=no  //用户是否可以通过他的手势来缩放整个应用程序，使应用程序的尺度发生一个改变（yes/no）
    -->
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <link rel="stylesheet" href="/front/bootstrap-3.3.6-dist/css/bootstrap.min.css">

    <title>个人中心</title>
    <style>
        *{
            marign:0;
            padding:0
        }
        li{
            list-style: none;
        }
        body {
            background: #f0f1f3;
            font-size: 14px;
        }
        .text-orange{
            color:#FF7F42;
        }
        .head-box {
            padding: 20px 15px;
            background: #0d73bd url("/front/bg.png");
            background-size: cover;
        }

        .head-img-box {
            margin-right: 2%;
            float: left;
        }

        .head-img {
            width: 80px;
            height: 80px;
        }

        .member-name-box {
            width: 70%;
            margin: 12px 0 0 0;
            float: left;
            font-size: 14px;
            color: #fff;
        }
        .account-box{
            width:100%;
            height:46px;
            line-height: 46px;
            display:flex;
        }
        .account-box li{
            float:left;
            flex:1;
            background: #fff;
            text-align: center;
        }
        .account-box li:first-child{
            margin-right:2px;
        }
        .menu-box{
            margin-top:15px;
        }
        .menu-box li{
            width:33%;
            margin:0 1px 1px 0;
            padding:20px 0;
            float:left;
            background: #fff;
            font-size:16px;
            color:#333;
            text-align: center;
        }
        .menu-box li:last-child(3),
        .menu-box li:last-child{
            margin-right:0;
        }
        .menu-box li .menu-icon{
            display: block;
            width:38px;
            height:38px;
            margin:0 auto 5px auto;
        }
        #qrcode {
            width:160px;
            height:160px;
            margin-top:15px;
        }  


        /*数量框*/
        .box{
               
              
                
               
            }
            .box button{
                width: 30px;
                border: 1px solid #dedede;
            }
            .box input{
                width: 40px;
                text-align: center;
            }
            #money{
                border: none;
                text-align: left;
                margin-left: 2px;
            }
           
 
    </style>
</head>
<body>
@include('front.head')
<!-- <ul class="account-box clearfix">
    <li>账户余额：<span class="text-primary">0</span> 元</li>
    <li>认证状态：<span class="text-orange">未认证</span></li>
</ul> -->
@if($data)
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">选择充值套餐:</div>

  <!-- Table -->
  
    @foreach($data as $v)
    <table class="table">
    <tr>
        <td>套餐</td>
        <td>{{$v->name}}</td>
    </tr>
    <tr> 
        <td>价格</td>   
        <td>
            <span class="label label-danger">￥<span id="money">{{$v->price_txt}}</span>/月</span>
        </td>
    </tr>
    @if($v->id==1)
    <tr>
        <td>数量</td>    
        <td class="box">
           
            <button id="plus">+</button>
            <input type="text" id="num" value="3"/>
            <button id="subtract">-</button>个月
            
        
        </td>
    </tr>
    @endif
    <tr>    
        <td colspan="2" style="text-align: right">
            <button  type="button"  data-id="{{$v->id}}" data-price="{{$v->price}}" class="btn btn-primary pay-btn" data-id="{{$v->id}}">充值</button>
        </td>
    </tr>
    </table>
    <hr/>
    @endforeach
   
    
    
  
 <!--  <div style="float: right;margin-right:10px; ">
    <button id="pay" class="btn btn-primary navbar-btn">充值</a>
  </div> -->
</div>
<div id="qrcode"></div>
@else
<div class="alert alert-info" role="alert">没有查询到可以充值得套餐</div>
@endif
<script src="/front/bootstrap-3.3.6-dist/js/jquery.min.js"></script>
<script src="/front/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.4.0.js"></script>
<script type="text/javascript" src="/js/jquery.qrcode.min.js"></script>
</body>
</html>
<script type="text/javascript">
    $('.pay-btn').click(function(){
        console.info('dianji');
        var data = {};
        var total_price  = 0;
        var num = 1;
        var id = $(this).data('id');
        if(id==1) {
             num  = $('#num').val();
        }
        
        var price        = $(this).data('price')
        total_price      = price*parseInt(num);
        data.dataplan_id = $(this).data('id');
        data.price  = total_price.toFixed(2);
        data.openid = "{{$user['openid']}}";
        data.iccid  = "{{$user['iccid']}}";
        data.num    = num;
        var url = "{{url('api/make-order')}}";
        $.post(url,data,function(rs){
            //alert(JSON.stringify(rs.data));
            if(rs.status==true) {
                wx.config({
                        debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
                        appId: rs.data.appId, // 必填，公众号的唯一标识
                        timestamp: rs.data.timeStamp, // 必填，生成签名的时间戳
                        nonceStr: rs.data.nonceStr, // 必填，生成签名的随机串
                         signature: rs.data.signJs,
                        jsApiList: ['chooseWXPay'] // 必填，需要使用的JS接口列表，这里只写支付的
                    });

                wx.chooseWXPay({  
                    
                                    appId:     rs.data.appId,
                                    timestamp: rs.data.timeStamp,  
                    nonceStr: rs.data.nonceStr,  
                    package:  rs.data.package,  
                    signType: rs.data.signType,  
                    paySign:  rs.data.paySign, // 支付签名  
                    success: function (res) {  
                        // 支付成功后的回调函数  
                        window.location.href='/';  
                    },fail:function(res){
                                        alert(JSON.stringify(res));
                                    }, cancel: function(res){
                                            alert('取消支付');
                                    }  
                });  
            } else {
                alert(JSON.stringify(rs));
            }            
        });  
    });

  $('#subtract').on('click',function(){
    var num = $('#num').val();
    if(num<2) {
        alert('购买数量不能小于1');
        return ;
    }
    $('#num').val(parseInt(num)-1);
    var price = $('.pay-btn').data('price');
    $('#money').val(num*price/100);

  }); 

  $('#plus').on('click',function(){
    var num = $('#num').val();
    $('#num').val(parseInt(num)+1);
    var price = $('.pay-btn').data('price');
    $('#money').val(num*price/100);

  });  

  
   
            


</script>

resources/views/front/query.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,height=device-height,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--1.width=device-width    //应用程序的宽度和屏幕的宽度是一样的
2.height=device-height  //应用程序的高度和屏幕的高是一样的
3.initial-scale=1.0  //应用程序启动时候的缩放尺度（1.0表示不缩放）
4.minimum-scale=1.0  //用户可以缩放到的最小尺度（1.0表示不缩放）
5.maximum-scale=1.0  //用户可以放大到的最大尺度（1.0表示不缩放）
6.user-scalable=no  //用户是否可以通过他的手势来缩放整个应用程序，使应用程序的尺度发生一个改变（yes/no）
    -->
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <link rel="stylesheet" href="/front/bootstrap-3.3.6-dist/css/bootstrap.min.css">

    <title>个人中心</title>
    <style>
        *{
            marign:0;
            padding:0
        }
        li{
            list-style: none;
        }
        body {
            background: #f0f1f3;
            font-size: 14px;
        }
        .text-orange{
            color:#FF7F42;
        }
        .head-box {
            padding: 20px 15px;
            background: #0d73bd url("/front/bg.png");
            background-size: cover;
        }

        .head-img-box {
            margin-right: 2%;
            float: left;
        }

        .head-img {
            width: 80px;
            height: 80px;
        }

        .member-name-box {
            width: 70%;
            margin: 12px 0 0 0;
            float: left;
            font-size: 14px;
            color: #fff;
        }
        .account-box{
            width:100%;
            height:46px;
            line-height: 46px;
            display:flex;
        }
        .account-box li{
            float:left;
            flex:1;
            background: #fff;
            text-align: center;
        }
        .account-box li:first-child{
            margin-right:2px;
        }
        .menu-box{
            margin-top:15px;
        }
        .menu-box li{
            width:33%;
            margin:0 1px 1px 0;
            padding:20px 0;
            float:left;
            background: #fff;
            font-size:16px;
            color:#333;
            text-align: center;
        }
        .menu-box li:last-child(3),
        .menu-box li:last-child{
            margin-right:0;
        }
        .menu-box li .menu-icon{
            display: block;
            width:38px;
            height:38px;
            margin:0 auto 5px auto;
        }
    </style>
</head>
<body>
@include('front.head')
<!-- <ul class="account-box clearfix">
    <li>账户余额：<span class="text-primary">0</span> 元</li>
    <li>认证状态：<span class="text-orange">未认证</span></li>
</ul> -->
@if($data)
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">流量查询结果:</div>

  <!-- Table -->
  @foreach($data as $k=>$v)
  <table class="table">
    <tr>
        <td>总流量</td><td>{{$v['total']}}</td>
    </tr>
   
    <tr>
        <td>已用流量</td><td>{{$v['used']}}</td>
    </tr>
   
    <tr>
        <td>剩余流量</td><td>{{$v['reset']}}</td>
    </tr>
    
     <tr>
        <td>生效日期</td><td>{{$v['validDate']}}</td>
    </tr>
     <tr>
        <td>失效日期</td><td>{{$v['expireDate']}}</td>
    </tr>
    
  </table>
  @endforeach
  <div style="float: right;margin-right:10px; ">
    <a href="{{url('/')}}" class="btn btn-primary navbar-btn">返回</a>
  </div>
</div>
@else
<div class="alert alert-info" role="alert">没有查询到流量数据</div>
@endif
<script src="/front/bootstrap-3.3.6-dist/js/jquery.min.js"></script>
<script src="/front/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
</body>
</html>